apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
spec:
  project: inventory
  source:
    repoURL: https://github.com/your-org/inventory-platform.git
    targetRevision: main
    path: helm/backend
  destination:
    - namespace: inventory
      server: https://kubernetes.default.svc
    - namespace: argocd   
      server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
