apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-app
  namespace: inventory
spec:
  project: inventory
  source:
    repoURL: https://github.com/your-org/inventory-platform.git
    targetRevision: main
    path: helm/frontend
  destination:
    name: inventory
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
